import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#99462a",
          50: "#fdf6f4",
          100: "#fbebe7",
          200: "#f7d7cf",
          300: "#f0baa8",
          400: "#e3937b",
          500: "#d97757",
          600: "#c45c3b",
          700: "#99462a",
          800: "#7f3a23",
          900: "#683321",
        },
        "primary-container": "#d97757",
        "on-primary": "#ffffff",
        "on-primary-container": "#541400",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#ffb59e",
        "on-primary-fixed": "#390b00",
        "on-primary-fixed-variant": "#7a2f15",

        secondary: {
          DEFAULT: "#446555",
          50: "#f3f8f5",
          100: "#e4f0e9",
          200: "#c6ebd7",
          300: "#a3d8be",
          400: "#6eb693",
          500: "#4a9473",
          600: "#446555",
          700: "#365144",
          800: "#2c4137",
          900: "#25372f",
        },
        "secondary-container": "#c6ebd7",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#4a6b5b",
        "secondary-fixed": "#c6ebd7",
        "secondary-fixed-dim": "#abcfbb",
        "on-secondary-fixed": "#002115",
        "on-secondary-fixed-variant": "#2d4d3e",

        tertiary: {
          DEFAULT: "#7d562d",
          container: "#b7895b",
        },
        "tertiary-container": "#b7895b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#422401",
        "tertiary-fixed": "#ffdcbd",
        "tertiary-fixed-dim": "#f0bd8b",
        "on-tertiary-fixed": "#2c1600",
        "on-tertiary-fixed-variant": "#623f18",

        surface: "#FAF8F5",
        "surface-bright": "#f7f9ff",
        "surface-dim": "#ccdcf0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f1ea",
        "surface-container": "#ede8df",
        "surface-container-high": "#e4dec7",
        "surface-container-highest": "#ded7ca",
        "surface-variant": "#ede8df",
        "surface-tint": "#99462a",

        "on-surface": "#0d1d2c",
        "on-surface-variant": "#55433d",
        "inverse-surface": "#233241",
        "inverse-on-surface": "#e9f1ff",
        "inverse-primary": "#ffb59e",

        outline: "#88726c",
        "outline-variant": "#dbc1b9",

        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        background: "#FAF8F5",
        foreground: "#0d1d2c",

        cream: "#FAF8F5",
        clay: "#D97757",
        terracotta: "#99462a",
        eucalyptus: "#446555",
        "wax-gold": "#D4A373",
      },
      fontFamily: {
        serif: ["'Playfair Display'", "serif"],
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        headline: ["'Playfair Display'", "serif"],
        display: ["'Playfair Display'", "serif"],
        body: ["'Plus Jakarta Sans'", "sans-serif"],
        label: ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Playfair Display'", "serif"],
        "headline-lg-mobile": ["'Playfair Display'", "serif"],
        "headline-sm": ["'Playfair Display'", "serif"],
        "display-lg": ["'Playfair Display'", "serif"],
        "display-lg-mobile": ["'Playfair Display'", "serif"],
        "title-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Playfair Display'", "serif"],
      },
      fontSize: {
        "headline-md": ["26px", { lineHeight: "34px", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["52px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "body-lg": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      boxShadow: {
        soft: "0 2px 15px -3px rgba(43, 58, 74, 0.06), 0 10px 20px -2px rgba(43, 58, 74, 0.03)",
        card: "0 1px 12px rgba(43, 58, 74, 0.05)",
        "card-hover": "0 8px 30px rgba(153, 70, 42, 0.12)",
        subtle: "0 2px 8px rgba(43, 58, 74, 0.04)",
      },
    },
  },
  plugins: [],
};

export default config;
